//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestaurantReviewSystem_WebClient.RestaurantServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Restaurant", Namespace="http://schemas.datacontract.org/2004/07/RestaurantReviewSystem")]
    [System.SerializableAttribute()]
    public partial class Restaurant : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long ContactNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CusineCategoryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImageNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RestaurantIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RestaurantNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string City {
            get {
                return this.CityField;
            }
            set {
                if ((object.ReferenceEquals(this.CityField, value) != true)) {
                    this.CityField = value;
                    this.RaisePropertyChanged("City");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long ContactNumber {
            get {
                return this.ContactNumberField;
            }
            set {
                if ((this.ContactNumberField.Equals(value) != true)) {
                    this.ContactNumberField = value;
                    this.RaisePropertyChanged("ContactNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CusineCategory {
            get {
                return this.CusineCategoryField;
            }
            set {
                if ((object.ReferenceEquals(this.CusineCategoryField, value) != true)) {
                    this.CusineCategoryField = value;
                    this.RaisePropertyChanged("CusineCategory");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmailAddress {
            get {
                return this.EmailAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailAddressField, value) != true)) {
                    this.EmailAddressField = value;
                    this.RaisePropertyChanged("EmailAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ImageName {
            get {
                return this.ImageNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ImageNameField, value) != true)) {
                    this.ImageNameField = value;
                    this.RaisePropertyChanged("ImageName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RestaurantId {
            get {
                return this.RestaurantIdField;
            }
            set {
                if ((this.RestaurantIdField.Equals(value) != true)) {
                    this.RestaurantIdField = value;
                    this.RaisePropertyChanged("RestaurantId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RestaurantName {
            get {
                return this.RestaurantNameField;
            }
            set {
                if ((object.ReferenceEquals(this.RestaurantNameField, value) != true)) {
                    this.RestaurantNameField = value;
                    this.RaisePropertyChanged("RestaurantName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RestaurantServiceReference.IRestaurantService")]
    public interface IRestaurantService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRestaurantService/GetRestaurant", ReplyAction="http://tempuri.org/IRestaurantService/GetRestaurantResponse")]
        System.Data.DataSet GetRestaurant();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRestaurantService/GetRestaurant", ReplyAction="http://tempuri.org/IRestaurantService/GetRestaurantResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetRestaurantAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRestaurantService/GetRestaurantById", ReplyAction="http://tempuri.org/IRestaurantService/GetRestaurantByIdResponse")]
        RestaurantReviewSystem_WebClient.RestaurantServiceReference.Restaurant GetRestaurantById(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRestaurantService/GetRestaurantById", ReplyAction="http://tempuri.org/IRestaurantService/GetRestaurantByIdResponse")]
        System.Threading.Tasks.Task<RestaurantReviewSystem_WebClient.RestaurantServiceReference.Restaurant> GetRestaurantByIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRestaurantService/AddRestaurant", ReplyAction="http://tempuri.org/IRestaurantService/AddRestaurantResponse")]
        string AddRestaurant(RestaurantReviewSystem_WebClient.RestaurantServiceReference.Restaurant restaurant);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRestaurantService/AddRestaurant", ReplyAction="http://tempuri.org/IRestaurantService/AddRestaurantResponse")]
        System.Threading.Tasks.Task<string> AddRestaurantAsync(RestaurantReviewSystem_WebClient.RestaurantServiceReference.Restaurant restaurant);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRestaurantService/DeleteRestaurant", ReplyAction="http://tempuri.org/IRestaurantService/DeleteRestaurantResponse")]
        string DeleteRestaurant(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRestaurantService/DeleteRestaurant", ReplyAction="http://tempuri.org/IRestaurantService/DeleteRestaurantResponse")]
        System.Threading.Tasks.Task<string> DeleteRestaurantAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRestaurantService/UpdateRestaurant", ReplyAction="http://tempuri.org/IRestaurantService/UpdateRestaurantResponse")]
        string UpdateRestaurant(RestaurantReviewSystem_WebClient.RestaurantServiceReference.Restaurant restaurant);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRestaurantService/UpdateRestaurant", ReplyAction="http://tempuri.org/IRestaurantService/UpdateRestaurantResponse")]
        System.Threading.Tasks.Task<string> UpdateRestaurantAsync(RestaurantReviewSystem_WebClient.RestaurantServiceReference.Restaurant restaurant);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRestaurantServiceChannel : RestaurantReviewSystem_WebClient.RestaurantServiceReference.IRestaurantService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RestaurantServiceClient : System.ServiceModel.ClientBase<RestaurantReviewSystem_WebClient.RestaurantServiceReference.IRestaurantService>, RestaurantReviewSystem_WebClient.RestaurantServiceReference.IRestaurantService {
        
        public RestaurantServiceClient() {
        }
        
        public RestaurantServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RestaurantServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RestaurantServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RestaurantServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet GetRestaurant() {
            return base.Channel.GetRestaurant();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetRestaurantAsync() {
            return base.Channel.GetRestaurantAsync();
        }
        
        public RestaurantReviewSystem_WebClient.RestaurantServiceReference.Restaurant GetRestaurantById(int id) {
            return base.Channel.GetRestaurantById(id);
        }
        
        public System.Threading.Tasks.Task<RestaurantReviewSystem_WebClient.RestaurantServiceReference.Restaurant> GetRestaurantByIdAsync(int id) {
            return base.Channel.GetRestaurantByIdAsync(id);
        }
        
        public string AddRestaurant(RestaurantReviewSystem_WebClient.RestaurantServiceReference.Restaurant restaurant) {
            return base.Channel.AddRestaurant(restaurant);
        }
        
        public System.Threading.Tasks.Task<string> AddRestaurantAsync(RestaurantReviewSystem_WebClient.RestaurantServiceReference.Restaurant restaurant) {
            return base.Channel.AddRestaurantAsync(restaurant);
        }
        
        public string DeleteRestaurant(int id) {
            return base.Channel.DeleteRestaurant(id);
        }
        
        public System.Threading.Tasks.Task<string> DeleteRestaurantAsync(int id) {
            return base.Channel.DeleteRestaurantAsync(id);
        }
        
        public string UpdateRestaurant(RestaurantReviewSystem_WebClient.RestaurantServiceReference.Restaurant restaurant) {
            return base.Channel.UpdateRestaurant(restaurant);
        }
        
        public System.Threading.Tasks.Task<string> UpdateRestaurantAsync(RestaurantReviewSystem_WebClient.RestaurantServiceReference.Restaurant restaurant) {
            return base.Channel.UpdateRestaurantAsync(restaurant);
        }
    }
}
